### PR TITLE
allow consuming code to make local dev less painful

### PR DESCRIPTION
**Pull request by yarmiganosca**
We want rails apps that use this to produce kafka messages to not require every contributor to have a running kafka on their machine. This method, called in an iniitializer, will allow branching based on connectivity, so that in local dev, a mock producer can be attached if necessary.

### CODE REVIEW

**Comment by babelfish** [comment]
KafkaSession defaults to using a mock producer?

**Comment by yarmiganosca** [comment]
Yup, that's the default.

**Comment by babelfish** [comment]
That feels off to me, like using a mock should be intentional and trying to use it without configuring a producer should be an error.

**Comment by yarmiganosca** [comment]
I can see that. Do you want that addressed now, or can we address it when I blow up this project & pull it into industrious core?

**Comment by babelfish** [comment]
That's fine.

**Pull request merged**
